### ISSUE TITLE
unable to open database file

### ISSUE THREAD

**Issue by Sim0nW0lf** [joshuaboniface/rffmpeg#38]
I just tried to rebuild my docker container and this happened. Not sure whats wrong 🤔
```
# docker exec -it jellyfin rffmpeg init

Traceback (most recent call last):
  File "/usr/local/bin/rffmpeg", line 831, in <module>
    run_control(config)
  File "/usr/local/bin/rffmpeg", line 819, in run_control
    return rffmpeg_click(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1256, in invoke
    Command.invoke(self, ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/rffmpeg", line 496, in rffmpeg_click
    with dbconn(config) as cur:
  File "/usr/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/bin/rffmpeg", line 50, in dbconn
    conn = sqlite_connect(config["db_path"])
sqlite3.OperationalError: unable to open database file
```

My Dockerfile hasn't changed:
```
FROM alpine AS qemu

# QEMU Download
ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v4.0.0%2Bbalena2/qemu-4.0.0.balena2-aarch64.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1

FROM --platform=linux/arm64 jellyfin/jellyfin:latest
#unstable
# Add QEMU
COPY --from=qemu qemu-aarch64-static /usr/bin

# Add Labels
LABEL maintainer admin@bitwrk.de

RUN apt update && \
    apt install -y openssh-client python3-click python3-yaml wget &&\
    wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg -O /usr/local/bin/rffmpeg && \
    chmod +x /usr/local/bin/rffmpeg && \
    ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffmpeg && \
    ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffprobe && \
    mkdir -p /etc/rffmpeg && \
    wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg.yml.sample -O /etc/rffmpeg/rffmpeg.yml && \
    #configure config
    sed -i 's;#persist: "/run/shm";persist: "/run";g' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#state: "/var/lib/rffmpeg";state: "/config/rffmpeg";g' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#pre:;pre:;g' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#    - "";    - "sudo";g' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#owner: jellyfin;owner: root;g' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;state: "/config/rffmpeg";state: "/var/lib/rffmpeg";g' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#user: jellyfin;user: ubuntu;g' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#persist: 300;persist: 0;g' /etc/rffmpeg/rffmpeg.yml && \

    #reinitialize rffmpeg
#    rffmpeg init -y && \
#    rffmpeg add Oracle4 && \
#    rffmpeg add Oracle5 && \
#    rffmpeg add Oracle6 && \
#    rffmpeg add Oracle7 && \
#    rffmpeg add Oracle8 && \   
    #clean up
    apt purge wget -y && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove --purge -y && \
    apt clean

ENTRYPOINT "./jellyfin/jellyfin"
```

**Comment by joshuaboniface** [comment]
I think I know the issue, will be fixed in the next commit.

**Comment by joshuaboniface** [comment]
Try now!

**Comment by Sim0nW0lf** [comment]
works perfectly 👌🏼
