### ISSUE TITLE
We're unable to find FFmpeg using the path you've entered.

### ISSUE THREAD

**Issue by aleksasiriski** [joshuaboniface/rffmpeg#39]
```We're unable to find FFmpeg using the path you've entered. FFprobe is also required and must exist in the same folder. These components are normally bundled together in the same download. Please check the path and try again.```

Using this [image](https://github.com/aleksasiriski/jellyfin-rffmpeg-server), you can read the Dockerfile [here](https://github.com/aleksasiriski/jellyfin-rffmpeg-server/blob/latest/Dockerfile).

The jellyfin nor the rffmpeg logs don't say anything in regards to this since I can't even save the Playback options.

I actually encountered this error [before](https://github.com/Shadowghost/jellyfin-rffmpeg/issues/4#issuecomment-1291191814) and it decided to fix itself somehow, now it's back with this new version of rffmpeg...

**Comment by joshuaboniface** [comment]
You might have hit the issue that @Sim0nW0lf just hit in the chat - where there was a bug due to me trying to "handle" SIGKILL. Is it still happening on a fresh build as of right now?

**Comment by aleksasiriski** [comment]
Actually I do get this in the logs when I try to save the Playback options:

```
2022-11-17 16:48:02,548 - rffmpeg[87] - INFO - Starting rffmpeg as /usr/local/bin/ffmpeg with args: -version
```

**Comment by aleksasiriski** [comment]
When I enable the debug in config I get this:

```
2022-11-17 16:50:44,732 - rffmpeg[509] - INFO - Starting rffmpeg as /usr/local/bin/ffmpeg with args: -version
2022-11-17 16:50:44,732 - rffmpeg[509] - DEBUG - Determining optimal target host
```

**Comment by aleksasiriski** [comment]
Here's the jellyfin logs:

```
[2022-11-17 16:50:44.701 +00:00] [INF] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Attempting to update encoder path to "/usr/local/bin/ffmpeg". pathType: "Custom"
[2022-11-17 16:50:44.736 +00:00] [ERR] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg validation: The process returned no result
[2022-11-17 16:50:44.736 +00:00] [ERR] [43] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/System/MediaEncoder/Path".
MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.UpdateEncoderPath(String path, String pathType)
   at Jellyfin.Api.Controllers.ConfigurationController.UpdateMediaEncoderPath(MediaEncoderPathDto mediaEncoderPath)
   at lambda_method892(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by joshuaboniface** [comment]
Looks like some more syntax errors, will fix up.

**Comment by aleksasiriski** [comment]
```
def get_target_host(config):
    """
    Determine an optimal target host via data on currently active processes and states.
    """
    log.debug("Determining optimal target host")
    # Select all hosts and active processes from the database
    with dbconn(config) as cur:
        hosts = cur.execute("SELECT * FROM hosts").fetchall()
        processes = cur.execute("SELECT * FROM processes").fetchall()

    # Generate a mapping dictionary of hosts and processes
    host_mappings = dict()
    for host in hosts:
        hid, hostname, weight, servername = host

        # Get the latest state
        with dbconn(config) as cur:
            current_state = cur.execute(
                "SELECT * FROM states WHERE host_id = ? ORDER BY id DESC", (hid,)
            ).fetchone()
```

Maybe there should be a check here if there are no hosts not to try and go through hosts, but I guess that for loop wouldn't execute and that shouldn't be a problem?

**Comment by Sim0nW0lf** [comment]
I can recreate this with no hosts added to the db.

**Comment by Sim0nW0lf** [comment]
hmm for me it's still not working. It should fall back to localhost right?

**Comment by joshuaboniface** [comment]
Yes, if no hosts are configured it will fall back to localhost because these values are None.

**Comment by aleksasiriski** [comment]
It's working for me, Github held a cache of the previous `rffmpeg` version for a few mins here..

**Comment by joshuaboniface** [comment]
```
joshua@base.bonifacelabs.net git:master ~/Projects/rffmpeg $ ./rffmpeg status
Hostname  Servername  ID  Weight  State  Active Commands
joshua@base.bonifacelabs.net git:master ~/Projects/rffmpeg $ ./ffmpeg -version
ffmpeg version 5.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
joshua@base.bonifacelabs.net git:master ~/Projects/rffmpeg $ tail /var/log/jellyfin/rffmpeg.log 
2022-11-17 12:00:16,699 - rffmpeg[250481] - DEBUG - Found optimal host ID None 'None' (None)
2022-11-17 12:00:16,699 - rffmpeg[250481] - INFO - Running command on host 'localhost'
2022-11-17 12:00:16,699 - rffmpeg[250481] - DEBUG - Local command: /usr/lib/jellyfin-ffmpeg/ffmpeg -version
2022-11-17 12:00:16,719 - rffmpeg[250481] - INFO - Finished rffmpeg with return code 0
2022-11-17 12:05:45,557 - rffmpeg[261665] - INFO - Starting rffmpeg as ./ffmpeg with args: -version
2022-11-17 12:05:45,557 - rffmpeg[261665] - DEBUG - Determining optimal target host
2022-11-17 12:05:45,558 - rffmpeg[261665] - DEBUG - Found optimal host ID None 'None' (None)
2022-11-17 12:05:45,558 - rffmpeg[261665] - INFO - Running command on host 'localhost'
2022-11-17 12:05:45,558 - rffmpeg[261665] - DEBUG - Local command: /usr/lib/jellyfin-ffmpeg/ffmpeg -version
2022-11-17 12:05:45,579 - rffmpeg[261665] - INFO - Finished rffmpeg with return code 0
```

Should be working there.

**Comment by joshuaboniface** [comment]
Excellent hopefully that's the last of the weird side-effects!
