### ISSUE TITLE
Repeat of issue #39 - ffmpeg validation failed

### ISSUE THREAD

**Issue by craiga1fix** [joshuaboniface/rffmpeg#46]
Hi,

I'm suffering from the same problem as others with Jellyfin not detecting the symlinked ffmpeg files.
A little different, I'm running Jellyfin on Free-BSD, but it's been working just fine for everything else. I'm also using rffmpeg to talk to ffmpeg on a Windows system, but it all seems to be working OK from the command line.

Running:
`sudo -u jellyfinserver /usr/local/bin/jrfm/ffmpeg -version`

Returns (as expected):
```
ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10-win32 (GCC) 20220324
configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lfftw3f -lstdc++' --extra-cflags=-DCH
ROMAPRINT_NODLL --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl
 --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libas
s --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-l
ibdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100

```

Checking status all looks ok:
`sudo -u jellyfinserver /usr/local/bin/rffmpeg status`
Hostname         Servername      ID  Weight  State  Active Commands
192.168.36.187  192.168.36.187  1   1            idle    N/A

When trying to add the ffmpeg path into Jellyfin, it immediately errors:
![image](https://user-images.githubusercontent.com/70143709/210468301-58910a3e-1519-40e7-8c28-9311eefa11b2.png)

The debug log from rffmpeg doesn't have any entry at all for any of these tries, it's like it's not hit the file (or at least not hit a logging point). It does have entries from my manual runs, so logging is OK.

JellyFin Log has the same error as other bugs:

[2023-01-04 01:33:08.496 +00:00] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Attempting to update encoder path to "/usr/local/bin/jrfm". pathType: "Custom"
[2023-01-04 01:33:08.500 +00:00] [ERR] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg validation: The process returned no result
[2023-01-04 01:33:08.504 +00:00] [ERR] [32] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/System/MediaEncoder/Path".
MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.UpdateEncoderPath(String path, String pathType)
   at Jellyfin.Api.Controllers.ConfigurationController.UpdateMediaEncoderPath(MediaEncoderPathDto mediaEncoderPath)
   at lambda_method1294(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)

Any clues on what I should try next?

**Comment by joshuaboniface** [comment]
Try setting the path to the full name (i.e. including `/ffmpeg`) rather than just the directory. I've not experienced this issue myself but I do set the full path. In either case this is a Jellyfin bug not an rffmpeg bug.

**Comment by craiga1fix** [comment]
Ok thanks - I've tried the full path and the directory and both fail. 
I'll see if I can get any help from the Jellyfin team on this one.

**Comment by craiga1fix** [comment]
Well, it's really weird - I already have debug logging on and when I select the folder with ffmpeg & ffprobe (the rffmpeg symlink versions) in Jellyfin and get the errror, absolutely nothing is written to the rffmpeg log file.

If I run rffmpeg as root or run it as the jellyfinserver user with sudo from the same location it works fine and outputs to the logfile as expected

It's like Jellyfin isn't even attempting to execute the file. 
It can definitely get to them:
![image](https://user-images.githubusercontent.com/70143709/211147380-8cc31235-699b-4f78-abe7-2d03a9b81984.png)

**Comment by joshuaboniface** [comment]
Very curious. Does Jellyfin write out any ffmpeg log files when it tries and fails to load it?

**Comment by aleksasiriski** [comment]
> Well, it's really weird - I already have debug logging on and when I select the folder with ffmpeg & ffprobe (the rffmpeg symlink versions) in Jellyfin and get the errror, absolutely nothing is written to the rffmpeg log file.
> 
> If I run rffmpeg as root or run it as the jellyfinserver user with sudo from the same location it works fine and outputs to the logfile as expected
> 
> It's like Jellyfin isn't even attempting to execute the file. It can definitely get to them: ![image](https://user-images.githubusercontent.com/70143709/211147380-8cc31235-699b-4f78-abe7-2d03a9b81984.png)

I have no experience running Jellyfin in FreeBSD jail but have you made sure the user jellyfin is using to run itself has readwriteexecute permissions on rffmpeg directory and all files within?

**Comment by aleksasiriski** [comment]
Is this fixed or do you need further assistence? No point in having stale issues open

**Comment by craiga1fix** [comment]
Apologies - busy few weeks. Just playing again.

> Very curious. Does Jellyfin write out any ffmpeg log files when it tries and fails to load it?

Yes, please see below:

> [2023-01-22 23:20:30.319 +00:00] [INF] [27] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Attempting to update encoder path to "/usr/local/bin/jrfm". pathType: "Custom"
[2023-01-22 23:20:30.352 +00:00] [ERR] [27] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg validation: The process returned no result
[2023-01-22 23:20:30.378 +00:00] [ERR] [27] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "POST" "/System/MediaEncoder/Path".
MediaBrowser.Common.Extensions.ResourceNotFoundException: Exception of type 'MediaBrowser.Common.Extensions.ResourceNotFoundException' was thrown.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.UpdateEncoderPath(String path, String pathType)
   at Jellyfin.Api.Controllers.ConfigurationController.UpdateMediaEncoderPath(MediaEncoderPathDto mediaEncoderPath)
   at lambda_method1294(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)



> I have no experience running Jellyfin in FreeBSD jail but have you made sure the user jellyfin is using to run itself has readwriteexecute permissions on rffmpeg directory and all files within?

It's not in a jail, just on plain FreeBSD.
Permissions are all OK as far as I can tell. Running ffmpeg (the rffmpeg version) via su as the "jellyfinserver" user (the user that the server is running jellyfin as) returns the expected version from the remote host.

**Comment by aleksasiriski** [comment]
You could try my [rewrite](https://github.com/aleksasiriski/rffmpeg-go) of this project, I'll soon release binaries (for FreeBSD as well as other OSes). Maybe python is acting up on your system..
