### ISSUE TITLE
Remote side quoting issue

### ISSUE THREAD

**Issue by bugsyb** [joshuaboniface/rffmpeg#74]
Big thanks to @joshuaboniface for this!
This problem is similar if not same as: https://github.com/joshuaboniface/rffmpeg/issues/28 though I couldn't find a solution there.
All set up and tests (version) works, paths are exact on both sides. Both sides are docker containers (different hosts) and data mapped via NFS - exact same paths.

The playback fails.

Any help in terms of troubleshooting would be great.

From my side tried with wrapper script on the remote side, though then it looses all quotes, probably mistake on my end:
wrapper on remote side
```
#!/bin/bash
LOG_FILE="/ram_transcode/ffmpeg-remote.log"

COMMAND="$0"
ARGS=("${@:1}")

# tested both options
#echo "Command: $COMMAND" >> "$LOG_FILE"
#echo "Arguments: ${ARGS[@]}" >> "$LOG_FILE"
echo "$0 $@" >> "$LOG_FILE"

exec "${COMMAND}.real" "${ARGS[@]}"

```

rffmpeg log
```
2023-10-08 15:05:02,929 - rffmpeg[15996] - INFO - Starting rffmpeg as /usr/local/bin/ffmpeg with args: -analyzeduration 200M -f matroska,webm -autorotate 0 -i file:/videos/private/Vide title  (1900)/Vide title  (1900) WEBDL-1080p.mkv -map_metadata -1 -map_chapters -1 -threads 5 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -preset ultrafast -crf 28 -maxrate 292000 -bufsize 584000 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 expr:gte(t,0+n_forced*3) -sc_threshold:v:0 0 -vf setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,426)/2)*2:trunc(ow/a/2)*2,format=yuv420p -codec:a:0 libfdk_aac -ac 2 -ab 128000 -af volume=2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename /ram_transcode/b935966a8c3f4b1c3539bc0b759118a5%d.ts -hls_playlist_type vod -hls_list_size 0 -y /ram_transcode/b935966a8c3f4b1c3539bc0b759118a5.m3u8
2023-10-08 15:05:02,929 - rffmpeg[15996] - DEBUG - Determining optimal target host
2023-10-08 15:05:02,930 - rffmpeg[15996] - DEBUG - Using SQLite as database.
2023-10-08 15:05:02,932 - rffmpeg[15996] - DEBUG - SQLite connection closed.
2023-10-08 15:05:02,932 - rffmpeg[15996] - DEBUG - Using SQLite as database.
2023-10-08 15:05:02,934 - rffmpeg[15996] - DEBUG - SQLite connection closed.
2023-10-08 15:05:02,934 - rffmpeg[15996] - DEBUG - Trying host ID 1 'rffmpeg.other.host'
2023-10-08 15:05:02,934 - rffmpeg[15996] - DEBUG - Running SSH test
2023-10-08 15:05:02,996 - rffmpeg[15996] - DEBUG - SSH test succeeded with retcode 0
2023-10-08 15:05:02,997 - rffmpeg[15996] - DEBUG - Selecting host as idle
2023-10-08 15:05:02,997 - rffmpeg[15996] - DEBUG - Found optimal host ID 1 'rffmpeg.other.host' (rffmpeg.other.host)
2023-10-08 15:05:02,998 - rffmpeg[15996] - INFO - Running command on host 'rffmpeg.other.host' (rffmpeg.other.host)
2023-10-08 15:05:02,999 - rffmpeg[15996] - DEBUG - Remote command: /usr/bin/ssh -q -t -o ConnectTimeout=1 -o ConnectionAttempts=1 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPath=/run//ssh-%r@%h:%p -o ControlPersist=300 -i /config/.ssh/id_rsa jellyfin@rffmpeg.other.host /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -f matroska,webm -autorotate 0 -i 'file:/videos/private/Vide title  (1900)/Vide title  (1900) WEBDL-1080p.mkv' -map_metadata -1 -map_chapters -1 -threads 5 -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -preset ultrafast -crf 28 -maxrate 292000 -bufsize 584000 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -force_key_frames:0 'expr:gte(t,0+n_forced*3)' -sc_threshold:v:0 0 -vf 'setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,426)/2)*2:trunc(ow/a/2)*2,format=yuv420p' -codec:a:0 libfdk_aac -ac 2 -ab 128000 -af volume=2 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_segment_filename /ram_transcode/b935966a8c3f4b1c3539bc0b759118a5%d.ts -hls_playlist_type vod -hls_list_size 0 -y /ram_transcode/b935966a8c3f4b1c3539bc0b759118a5.m3u8
2023-10-08 15:05:03,000 - rffmpeg[15996] - DEBUG - Using SQLite as database.
2023-10-08 15:05:03,013 - rffmpeg[15996] - DEBUG - SQLite connection closed.
2023-10-08 15:05:03,363 - rffmpeg[15996] - DEBUG - Using SQLite as database.
2023-10-08 15:05:03,375 - rffmpeg[15996] - DEBUG - SQLite connection closed.
2023-10-08 15:05:03,375 - rffmpeg[15996] - ERROR - Finished rffmpeg with return code 1
```

Jellyfin side - for whatever reason it shows /videos in path. Though it is URL/URI based and not filesystem based - hence the suspicion, problem is there.
```
[2023-10-08 15:05:03.426 +02:00] [ERR] [86] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[2023-10-08 15:05:03.446 +02:00] [ERR] [60] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/58b6fecc-97e3-fba5-039c-617abfb3e88e/hls1/main/0.ts".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method1130(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

**Comment by bugsyb** [comment]
Closed - error between keyboard and the screen. I couldn't believe it doesn't work as if it would be true bug, it should fail for close to everyone.

Problem was - NFS exported folder, on Jellyfin container side, runs as root, rffmpeg worker, used other user - lack of privileges for that user to write to ram_transcode folder.

Hope it helps others.
