### ISSUE TITLE
Can´t get version

### ISSUE THREAD

**Issue by Y0ngg4n** [joshuaboniface/rffmpeg#87]
```
ffmpeg -version
Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg", line 563, in run_ffmpeg
    ret = run_local_ffmpeg(config, ffmpeg_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: run_local_ffmpeg() missing 1 required positional argument: 'ffmpeg_args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ffmpeg", line 1045, in <module>
    run_ffmpeg(config, ffmpeg_args)
  File "/usr/local/bin/ffmpeg", line 575, in run_ffmpeg
    log.error(f"Finished rffmpeg with return code {ret.returncode}")
                                                   ^^^
UnboundLocalError: cannot access local variable 'ret' where it is not associated with a value
```

**Comment by joshuaboniface** [comment]
The fix I just pushed should solve that, but let me know if it doesn't.

**Comment by Y0ngg4n** [comment]
@joshuaboniface thank you i will test it
